### ISSUE TITLE
Date parsing error

### ISSUE THREAD

**Issue by AndreiMaz** [nopSolutions/shipstation-plugin-for-nopcommerce#1]
Hi, I am testing your plugin for ShipStation, and I am getting the below error in ShipStation. Can you let me know what is the problem.

07/12/2016 02:52 pm javierpalaciosmcp@hotmail.com
An error occurred attempting to update orders: Error in XML. Reason: The 'OrderDate' element is invalid - The value '07-12-2016 18:27' is invalid according to its datatype 'DateTime' - The Pattern constraint failed.

**Comment by skoshelev** [comment]
Closed #1
