### ISSUE TITLE
Bugs on 4.4 version

### ISSUE THREAD

**Issue by ghost** [nopSolutions/shipstation-plugin-for-nopcommerce#10]
There are spaces in the names of "PostalCode" and "OrderStatus" that cause XML errors in ShipStationService.cs:
`await writer.WriteElementStringAsync("PostalCode ", address.ZipPostalCode);`

`await writer.WriteElementStringAsync("OrderStatus ", GetOrderStatus(order));`

I also found that when no orders are found, GetXmlOrdersAsync returns a blank string. I was able to fix this by adding:
`await writer.FlushAsync();`

right before the stream is encoded.

**Comment by AndreiMaz** [comment]
Thanks a lot for reporting. But already fixed. Please see https://github.com/nopSolutions/nopCommerce/issues/5684 and https://github.com/nopSolutions/nopCommerce/commit/2569a15f0141807f2746088fc16bb20c8d23e1f3#diff-13227cc531b1f5a8ef3bf7557727791b763f2ebe6aaa1c44085458b63993b5d9
