### ISSUE TITLE
Shipment can't be created

### ISSUE THREAD

**Issue by jbrandt-q5** [nopSolutions/shipstation-plugin-for-nopcommerce#9]
An error occurs in CreateOrUpadeteShipping because it's trying to add a ShipmentItem before adding a Shipment. 

Bug was addressed by Yidna here but as far as I can tell the fix wasn't added to the code. 

https://www.nopcommerce.com/en/boards/topic/85274/430-how-to-get-shipments-in-order-from-plugin

**Comment by AndreiMaz** [comment]
It's not a bug. Just save a shipment first, and then you can insert shipment items

**Comment by jbrandt-q5** [comment]
How is it not a bug? It literally adds an error in the Nop log. If this isn't a bug be sure to add instructions to the documentation that says "if you want to use the automated ShipStation shipment creation be sure to create your shipment manually first."

**Comment by skoshelev** [comment]
Hi @jbrandt-q5.

yes, you are right, this is a bug, but it was fixed long ago, see [this issue](https://github.com/nopSolutions/nopCommerce/issues/5006)
